name: android

on: 
  push:
    branches:
      - dev

    paths-ignore:
      - '**.md'
      - 'docs/**'
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  GH_OS_NAME: linux
  BUILD_TARGET: android
  BUILD_TYPE: Release

jobs:
  build:
    if: ${{ !startsWith(github.event.commits[0].message, 'Merge pull request') }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - armv7
          - arm64
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: actions/setup-java@v3
      with:
        distribution: 'microsoft' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      shell: pwsh
      run: |
        $AX_ROOT = $(Get-Location).Path
        ./build.ps1 -p android -a $env:BUILD_ARCH

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.arch }}
        path: |
          templates/**/*.apk
          tests/**/*.apk
