name: genbindings

on: 
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Python
      uses: actions/setup-python@v4

    - name: Build
      run: tools\win-ci\genbindings.ps1
      
    - name: Commit genbindings changes
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Committing genbindings changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
