name: linux

on: 
  push:
    branches:
      - dev

    paths-ignore:
      - '**.md'
      - '**/*.md.in'
      - 'docs/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  GH_OS_NAME: linux
  BUILD_TARGET: linux
  BUILD_TYPE: Release

jobs:
  build:
    if: ${{ !startsWith(github.event.commits[0].message, 'Merge pull request') }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: |
        AX_ROOT=`pwd`
        echo -e "y" | pwsh $AX_ROOT/setup.ps1

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      shell: pwsh
      run: ./build.ps1 -p linux -a x64
