name: osx

on: 
  push:
    branches:
      - dev

    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  GH_OS_NAME: osx
  BUILD_TARGET: osx
  BUILD_TYPE: Release

jobs:
  build:
    if: ${{ !startsWith(github.event.commits[0].message, 'Merge pull request') }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    strategy:
      matrix:
        arch:
          - x64
          - arm64
    env:
      BUILD_ARCH: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      shell: pwsh
      run: ./build.ps1 -p osx -a $env:BUILD_ARCH
