name: pull_request

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PYENV_VERSION: 2.7.18
  PULL_REQUEST: yes

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - {arch: x86, dll: false}
          - {arch: x64, dll: false}
          - {arch: x86, dll: true}
          - {arch: x64, dll: true}
    env:
      BUILD_ARCH: ${{ matrix.config.arch }}
      BUILD_DLL: ${{ matrix.config.dll }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v3
      - uses: ilammy/msvc-dev-cmd@v1.12.0
        with: 
          arch: ${{ env.BUILD_ARCH }}
      - name: Build
        run: tools\win-ci\build.ps1 $env:BUILD_ARCH $env:BUILD_DLL

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    env:
      GH_OS_NAME: linux
      BUILD_TARGET: linux
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          tools/unix-ci/before-install.sh
          tools/unix-ci/run-script.sh

  build-android:
    name: build-android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
    env:
      GH_OS_NAME: linux
      BUILD_TARGET: android
      BUILD_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build
        run: |
          tools/unix-ci/before-install.sh
          tools/unix-ci/run-script.sh

  build-osx:
    name: build-osx
    runs-on: macos-12
    strategy:
      matrix:
        arch:
          - x86_64
          - arm64
    env:
      GH_OS_NAME: osx
      BUILD_TARGET: osx
      BUILD_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          tools/unix-ci/before-install.sh
          tools/unix-ci/run-script.sh

  build-ios:
    name: build-ios
    runs-on: macos-latest
    env:
      GH_OS_NAME: osx
      BUILD_TARGET: ios
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          tools/unix-ci/before-install.sh
          tools/unix-ci/run-script.sh

  build-tvos:
    name: build-tvos
    runs-on: macos-latest
    env:
      GH_OS_NAME: osx
      BUILD_TARGET: tvos
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          tools/unix-ci/before-install.sh
          tools/unix-ci/run-script.sh
