name: publish

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
         # actions run ID
         description: 'Please input release version'
         # Default value if no value is explicitly provided
         default: ''
         # Input has to be provided for the workflow to run
         required: false
jobs:
  publish:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Make package
      id: make_pkg

      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      shell: pwsh
      run: |
        .\build.ps1 -p win32 -xc '-DAX_WITH_LZ4=ON,-DAX_WITH_CARES=ON,-DAX_WITH_YAML_CPP=ON,-DAX_WITH_KCP=ON,-DAX_WITH_OBOE=ON' -c
        .\tools\ci\make-pkg.ps1 -version "${{ github.event.inputs.version }}"
        ls

    - name: Publish to github release page
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.make_pkg.outputs.release_tag }}
        name: ${{ steps.make_pkg.outputs.release_tag }}
        files: ${{ steps.make_pkg.outputs.release_pkg }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: simdsoft/axmol